name: Build and push agent v1alpha1 CRDs

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  yoke-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push agent v1alpha1 CRDs
        run: |
          go install github.com/yokecd/yoke/cmd/yoke

          cd ./internal/k8s/agent/v1alpha1
          ./push.sh
